import { NextResponse } from "next/server";

interface BOMItem {
  catalog: string;
  quantity: string;
  description: string;
  estCost: string;
}

interface QuotePayload {
  jobName: string;
  jobId: string;
  city: string;
  zip: string;
  elliottStore: string | null;
  elliottRep: string | null;
  bom: BOMItem[];
  notes: string;
  userEmail: string;
  companyName: string | null;
  phone: string | null;
}

export async function POST(request: Request) {
  try {
    const payload: QuotePayload = await request.json();

    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) {
      console.error("[quote-request] No RESEND_API_KEY configured");
      return NextResponse.json(
        { ok: false, error: "Email service not configured" },
        { status: 500 }
      );
    }

    // Build the BOM table as clean text
    const bomLines = payload.bom.map(
      (item) => `${item.quantity.padEnd(8)} ${item.catalog.padEnd(24)} ${item.description}`
    );

    const storeInfo = payload.elliottStore
      ? `Preferred Store: ${payload.elliottStore}`
      : "No store preference";
    const repInfo = payload.elliottRep
      ? `Sales Rep: ${payload.elliottRep}`
      : "";

    const emailBody = `
VOLTSPEC QUOTE REQUEST
${"═".repeat(60)}

Job:     ${payload.jobName}
City:    ${payload.city}
ZIP:     ${payload.zip}
Date:    ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

${storeInfo}
${repInfo}

Customer:  ${payload.companyName || "(not provided)"}
Email:     ${payload.userEmail}
Phone:     ${payload.phone || "(not provided)"}

${"─".repeat(60)}
BILL OF MATERIALS
${"─".repeat(60)}
QTY      CATALOG #                DESCRIPTION
${bomLines.join("\n")}
${"─".repeat(60)}

${payload.notes ? `NOTES:\n${payload.notes}\n` : ""}
${"─".repeat(60)}
Generated by VoltSpec — voltspec.online
Reference pricing only. Please provide current cash-sale quote.
    `.trim();

    const emailHtml = `
<div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto;">
  <div style="background: #0f172a; padding: 20px 24px; border-radius: 8px 8px 0 0;">
    <h1 style="color: #facc15; margin: 0; font-size: 20px;">⚡ VoltSpec Quote Request</h1>
  </div>
  <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0;">
    <table style="width: 100%; margin-bottom: 16px; font-size: 14px;">
      <tr><td style="color: #64748b; padding: 4px 0;">Job:</td><td style="font-weight: bold;">${payload.jobName}</td></tr>
      <tr><td style="color: #64748b; padding: 4px 0;">City / ZIP:</td><td>${payload.city} ${payload.zip}</td></tr>
      <tr><td style="color: #64748b; padding: 4px 0;">Customer:</td><td>${payload.companyName || payload.userEmail}</td></tr>
      <tr><td style="color: #64748b; padding: 4px 0;">Email:</td><td><a href="mailto:${payload.userEmail}">${payload.userEmail}</a></td></tr>
      ${payload.phone ? `<tr><td style="color: #64748b; padding: 4px 0;">Phone:</td><td>${payload.phone}</td></tr>` : ""}
      ${payload.elliottStore ? `<tr><td style="color: #64748b; padding: 4px 0;">Store:</td><td>${payload.elliottStore}</td></tr>` : ""}
      ${payload.elliottRep ? `<tr><td style="color: #64748b; padding: 4px 0;">Sales Rep:</td><td>${payload.elliottRep}</td></tr>` : ""}
    </table>

    <h3 style="color: #0f172a; border-bottom: 2px solid #facc15; padding-bottom: 6px;">Bill of Materials</h3>
    <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
      <thead>
        <tr style="background: #0f172a; color: white;">
          <th style="padding: 8px; text-align: left;">Qty</th>
          <th style="padding: 8px; text-align: left;">Catalog #</th>
          <th style="padding: 8px; text-align: left;">Description</th>
          <th style="padding: 8px; text-align: right;">Est. Cost</th>
        </tr>
      </thead>
      <tbody>
        ${payload.bom
          .map(
            (item, i) => `
          <tr style="background: ${i % 2 === 0 ? "#ffffff" : "#f1f5f9"};">
            <td style="padding: 6px 8px;">${item.quantity}</td>
            <td style="padding: 6px 8px; font-family: monospace;">${item.catalog}</td>
            <td style="padding: 6px 8px;">${item.description}</td>
            <td style="padding: 6px 8px; text-align: right;">${item.estCost}</td>
          </tr>`
          )
          .join("")}
      </tbody>
    </table>

    ${payload.notes ? `<div style="margin-top: 16px; padding: 12px; background: #fffbeb; border-left: 4px solid #facc15; font-size: 14px;"><strong>Notes:</strong> ${payload.notes}</div>` : ""}
  </div>
  <div style="background: #0f172a; padding: 12px 24px; border-radius: 0 0 8px 8px; text-align: center;">
    <span style="color: #64748b; font-size: 12px;">Generated by <a href="https://voltspec.online" style="color: #facc15;">VoltSpec</a> — Reference pricing only</span>
  </div>
</div>`;

    // Send via Resend
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "VoltSpec <onboarding@resend.dev>",
        to: [payload.userEmail],
        subject: `Quote Request – ${payload.jobName} – ${payload.city}`,
        text: emailBody,
        html: emailHtml,
      }),
    });

    const resBody = await res.json();
    console.log("[quote-request] Resend response:", res.status, JSON.stringify(resBody));

    if (!res.ok) {
      console.error("[quote-request] Resend error:", resBody);
      return NextResponse.json(
        { ok: false, error: resBody?.message || "Email send failed" },
        { status: 502 }
      );
    }

    return NextResponse.json({ ok: true, emailSent: true, id: resBody.id });
  } catch (err) {
    console.error("[quote-request] Error:", err);
    return NextResponse.json(
      { ok: false, error: String(err) },
      { status: 500 }
    );
  }
}
